cucumber.publish.quiet=true
cucumber.plugin=pretty,\
  json:build/reports/cucumber/report.json,\
  lsd.cucumber.LsdCucumberPlugin
cucumber.features=classpath:io/lsdconsulting/example/activityengine
cucumber.glue=io.lsdconsulting.example.activityengine
cucumber.filter.tags=not @wip
cucumber.execution.parallel.enabled=false
