# This workflow will build a Java project with Gradle then perform an automated release
# For more information see:
#  https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
#  https://github.com/marketplace/actions/action-for-semantic-release

name: CI
on: [ push, pull_request ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish LSD report
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: service/build/reports/lsd
      - uses: actions/upload-artifact@v3
        with:
          name: build-directory
          path: service/build
      - uses: codecov/codecov-action@v5
        with:
          files: service/build/reports/jacoco/test/jacocoTestReport.xml
          verbose: true
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
          files: "service/build/test-results/**/*.xml"
